//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FasCon.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Users1 = new HashSet<User>();
            this.Users11 = new HashSet<User>();
        }
    
        public System.Guid UserID { get; set; }
        public string AspNetUserID { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.Guid CreateUserID { get; set; }
        public System.Guid UpdateUserID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<User> Users1 { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<User> Users11 { get; set; }
        public virtual User User2 { get; set; }
    }
}
